### ISSUE TITLE
Arrows are fucked (Suggestion)

### ISSUE THREAD

**Issue by IDespiseYouAll** [CoolDude53/FK-Issue-Logging#518]
As of right now, the amount of arrows you get per tier of log at the roaming trader has some problems. I tested every log and below are the results.

tier 1 log + 4g = 2 arrows
tier 2 log + 6g = 3 arrows
tier 3 log + 8g = 4 arrows
tier 4 log + 10g = 5 arrows
tier 5 log + 12g = 6 arrows

The problem with this is the following: **Each arrow costs the same amount**. As you can see, no matter the tier of log, every arrow costs the same amount, which is 2g per arrow. The only advantage of higher tier logs is that you can buy more arrows at once, while tier 5 logs are significantly harder to get than tier 1 logs yet barely give more arrows (3 tier 1 logs will give the same amount of arrows as a tier 5 log)

Personally, i'd like to see the return of tiered arrows, and perhaps add an alchemist trade for them (x amount of tier 1 arrows = y amount of tier 2 arrows)

**Comment by nrpritchard** [comment]
Being worked out on trello
